import colorama import Fore, Style, init
init(autorest=True)
print(Fore.RED + Style.BRIGHT)
print("💕 eu_te_amo💕\n")
print(Fore.WHITE + Style.NORMAL)
print("font-family: 'Meu amor';")
print("color: #fff;")
print("font-size: 2.5rem;")
print("font-weight: 300;")
print("letter-spacing: 2px;")
